# Prettier configuration
plugins:
  - "prettier-plugin-java"
  - "@prettier/plugin-xml"
overrides:
  - files:
      - "*.java"
    options:
      printWidth: 140
      tabWidth: 2
      useTabs: false
  - files:
      - "*.xml"
    options:
      xmlWhitespaceSensitivity: "strict"
      tabWidth: 2
      useTabs: false
  - files:
      - "*.ftlh"
    options:
      parser: "html"
      xmlWhitespaceSensitivity: "strict"
